services:
  pokeserver:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "7171:7171"
      - "7172:7172"
    volumes:
      - ./data:/app/forgottenserver/data
      - ./config.lua:/app/forgottenserver/config.lua
    depends_on:
      - db
    networks:
      - forgottenserver-network
  db:
    context: ./docker/db
    dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=abc123
      - MYSQL_DATABASE=forgotten
      - MYSQL_USER=root
      - MYSQL_PASSWORD=abc123
    ports:
      - "3306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - forgottenserver-network

networks:
  forgottenserver-network:
    driver: bridge